language: node_js

cache: npm

# install dependencies
install:
  - npm install --silent

# the jobs for building and deploying
jobs:
  include:
#    - stage: lint
#      script:
#        - npm run lint
#
#    - stage: test
#      script:
#        - npm run test:ci

    - stage: build
      script:
        # build polyfill
        - npm run build
        # create the target
        - mkdir -p ./gh-pages/dist
        # copy the built folder and html to target
        - cp -R dist/* ./gh-pages/dist
        - cp index.html README.md ./gh-pages

    - stage: deploy
      name: "github pages"
      if: branch = master
      provider: pages
      skip-cleanup: true
      keep-history: true
      local-dir: gh-pages
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      on:
        branch: master

    - stage: deploy
      name: "npm release"
      script:
        - ls -lah
      deploy:
        provider: npm
        skip-cleanup: true
        keep-history: true
        local-dir: dist
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        on:
          branch: develop
#          tags: true
